#pragma once
#include <gl/glew.h>
#include <gl/glfw3.h>
#include <vector>
#include <string>
#include <memory>
#include <algorithm>
#include <iostream>
#include "AppContext.h"
#include "ColliderManager.h"
#include "Object.h"
#include "Transform.h"
#include "MeshRenderer2D.h"